/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SessionAppelsRouteImport } from './routes/session-appels'
import { Route as QualificationRouteImport } from './routes/qualification'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IntegrationProspectsRouteImport } from './routes/integration-prospects'
import { Route as GroupesRouteImport } from './routes/groupes'
import { Route as DemainRouteImport } from './routes/demain'
import { Route as AujourdhuiRouteImport } from './routes/aujourdhui'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionAppelsRoute = SessionAppelsRouteImport.update({
  id: '/session-appels',
  path: '/session-appels',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificationRoute = QualificationRouteImport.update({
  id: '/qualification',
  path: '/qualification',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationProspectsRoute = IntegrationProspectsRouteImport.update({
  id: '/integration-prospects',
  path: '/integration-prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupesRoute = GroupesRouteImport.update({
  id: '/groupes',
  path: '/groupes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemainRoute = DemainRouteImport.update({
  id: '/demain',
  path: '/demain',
  getParentRoute: () => rootRouteImport,
} as any)
const AujourdhuiRoute = AujourdhuiRouteImport.update({
  id: '/aujourdhui',
  path: '/aujourdhui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/demain': typeof DemainRoute
  '/groupes': typeof GroupesRoute
  '/integration-prospects': typeof IntegrationProspectsRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/parking': typeof ParkingRoute
  '/prospects': typeof ProspectsRoute
  '/qualification': typeof QualificationRoute
  '/session-appels': typeof SessionAppelsRoute
  '/stats': typeof StatsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/demain': typeof DemainRoute
  '/groupes': typeof GroupesRoute
  '/integration-prospects': typeof IntegrationProspectsRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/parking': typeof ParkingRoute
  '/prospects': typeof ProspectsRoute
  '/qualification': typeof QualificationRoute
  '/session-appels': typeof SessionAppelsRoute
  '/stats': typeof StatsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/demain': typeof DemainRoute
  '/groupes': typeof GroupesRoute
  '/integration-prospects': typeof IntegrationProspectsRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/parking': typeof ParkingRoute
  '/prospects': typeof ProspectsRoute
  '/qualification': typeof QualificationRoute
  '/session-appels': typeof SessionAppelsRoute
  '/stats': typeof StatsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aujourdhui'
    | '/demain'
    | '/groupes'
    | '/integration-prospects'
    | '/journal'
    | '/login'
    | '/mcp'
    | '/parking'
    | '/prospects'
    | '/qualification'
    | '/session-appels'
    | '/stats'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aujourdhui'
    | '/demain'
    | '/groupes'
    | '/integration-prospects'
    | '/journal'
    | '/login'
    | '/mcp'
    | '/parking'
    | '/prospects'
    | '/qualification'
    | '/session-appels'
    | '/stats'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/aujourdhui'
    | '/demain'
    | '/groupes'
    | '/integration-prospects'
    | '/journal'
    | '/login'
    | '/mcp'
    | '/parking'
    | '/prospects'
    | '/qualification'
    | '/session-appels'
    | '/stats'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AujourdhuiRoute: typeof AujourdhuiRoute
  DemainRoute: typeof DemainRoute
  GroupesRoute: typeof GroupesRoute
  IntegrationProspectsRoute: typeof IntegrationProspectsRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ParkingRoute: typeof ParkingRoute
  ProspectsRoute: typeof ProspectsRoute
  QualificationRoute: typeof QualificationRoute
  SessionAppelsRoute: typeof SessionAppelsRoute
  StatsRoute: typeof StatsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-appels': {
      id: '/session-appels'
      path: '/session-appels'
      fullPath: '/session-appels'
      preLoaderRoute: typeof SessionAppelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualification': {
      id: '/qualification'
      path: '/qualification'
      fullPath: '/qualification'
      preLoaderRoute: typeof QualificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-prospects': {
      id: '/integration-prospects'
      path: '/integration-prospects'
      fullPath: '/integration-prospects'
      preLoaderRoute: typeof IntegrationProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupes': {
      id: '/groupes'
      path: '/groupes'
      fullPath: '/groupes'
      preLoaderRoute: typeof GroupesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demain': {
      id: '/demain'
      path: '/demain'
      fullPath: '/demain'
      preLoaderRoute: typeof DemainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aujourdhui': {
      id: '/aujourdhui'
      path: '/aujourdhui'
      fullPath: '/aujourdhui'
      preLoaderRoute: typeof AujourdhuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AujourdhuiRoute: AujourdhuiRoute,
  DemainRoute: DemainRoute,
  GroupesRoute: GroupesRoute,
  IntegrationProspectsRoute: IntegrationProspectsRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ParkingRoute: ParkingRoute,
  ProspectsRoute: ProspectsRoute,
  QualificationRoute: QualificationRoute,
  SessionAppelsRoute: SessionAppelsRoute,
  StatsRoute: StatsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
