/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionAppelsRouteImport } from './routes/session-appels'
import { Route as IndexRouteImport } from './routes/index'

const SessionAppelsRoute = SessionAppelsRouteImport.update({
  id: '/session-appels',
  path: '/session-appels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session-appels': typeof SessionAppelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/session-appels': typeof SessionAppelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session-appels': typeof SessionAppelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/session-appels'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/session-appels'
  id: '__root__' | '/' | '/session-appels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionAppelsRoute: typeof SessionAppelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session-appels': {
      id: '/session-appels'
      path: '/session-appels'
      fullPath: '/session-appels'
      preLoaderRoute: typeof SessionAppelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionAppelsRoute: SessionAppelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
