/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SessionAppelsRouteImport } from './routes/session-appels'
import { Route as ProspectsRouteImport } from './routes/prospects'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IntegrationProspectsRouteImport } from './routes/integration-prospects'
import { Route as AujourdhuiRouteImport } from './routes/aujourdhui'
import { Route as IndexRouteImport } from './routes/index'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionAppelsRoute = SessionAppelsRouteImport.update({
  id: '/session-appels',
  path: '/session-appels',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectsRoute = ProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationProspectsRoute = IntegrationProspectsRouteImport.update({
  id: '/integration-prospects',
  path: '/integration-prospects',
  getParentRoute: () => rootRouteImport,
} as any)
const AujourdhuiRoute = AujourdhuiRouteImport.update({
  id: '/aujourdhui',
  path: '/aujourdhui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/integration-prospects': typeof IntegrationProspectsRoute
  '/journal': typeof JournalRoute
  '/process': typeof ProcessRoute
  '/prospects': typeof ProspectsRoute
  '/session-appels': typeof SessionAppelsRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/integration-prospects': typeof IntegrationProspectsRoute
  '/journal': typeof JournalRoute
  '/process': typeof ProcessRoute
  '/prospects': typeof ProspectsRoute
  '/session-appels': typeof SessionAppelsRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aujourdhui': typeof AujourdhuiRoute
  '/integration-prospects': typeof IntegrationProspectsRoute
  '/journal': typeof JournalRoute
  '/process': typeof ProcessRoute
  '/prospects': typeof ProspectsRoute
  '/session-appels': typeof SessionAppelsRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aujourdhui'
    | '/integration-prospects'
    | '/journal'
    | '/process'
    | '/prospects'
    | '/session-appels'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aujourdhui'
    | '/integration-prospects'
    | '/journal'
    | '/process'
    | '/prospects'
    | '/session-appels'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/aujourdhui'
    | '/integration-prospects'
    | '/journal'
    | '/process'
    | '/prospects'
    | '/session-appels'
    | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AujourdhuiRoute: typeof AujourdhuiRoute
  IntegrationProspectsRoute: typeof IntegrationProspectsRoute
  JournalRoute: typeof JournalRoute
  ProcessRoute: typeof ProcessRoute
  ProspectsRoute: typeof ProspectsRoute
  SessionAppelsRoute: typeof SessionAppelsRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-appels': {
      id: '/session-appels'
      path: '/session-appels'
      fullPath: '/session-appels'
      preLoaderRoute: typeof SessionAppelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospects': {
      id: '/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof ProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-prospects': {
      id: '/integration-prospects'
      path: '/integration-prospects'
      fullPath: '/integration-prospects'
      preLoaderRoute: typeof IntegrationProspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aujourdhui': {
      id: '/aujourdhui'
      path: '/aujourdhui'
      fullPath: '/aujourdhui'
      preLoaderRoute: typeof AujourdhuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AujourdhuiRoute: AujourdhuiRoute,
  IntegrationProspectsRoute: IntegrationProspectsRoute,
  JournalRoute: JournalRoute,
  ProcessRoute: ProcessRoute,
  ProspectsRoute: ProspectsRoute,
  SessionAppelsRoute: SessionAppelsRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
